# Generated by Django 5.2.8 on 2025-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='photo/products'),
        ),
    ]
