# Generated by Django 5.2.8 on 2025-12-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
